### ISSUE TITLE
Missing evaluation datasets in Table 1 of the paper

### ISSUE THREAD

**Issue by BuddhiWathsala** [DerekQXu/GLSearch#4]
I noticed that some of the evaluation datasets are missing in the link [1] that you have given. Especially, the following datasets in Table 1 of your paper [2].
- ER-50
- ER-100

Am I missing something here or did you intentionally not publish those synthetic datasets?

## References
[1] https://drive.google.com/drive/folders/1l7_WmO54gPHZ4YwzOqewZtZhWIxn44ZV?usp=sharing
[2] http://proceedings.mlr.press/v139/bai21e/bai21e.pdf

**Comment by DerekQXu** [comment]
Hi, you can generate those datasets with the following setting in `config.py`:
```
        dataset_list = [
            ([('syn:np_tr=20,np_te=50,nn_core=-1,nn_tot=50,ed=5,gen_type=BA', -1),
              ('syn:np_tr=20,np_te=50,nn_core=-1,nn_tot=50,ed=0.08,gen_type=ER', -1),
              ('syn:np_tr=20,np_te=50,nn_core=-1,nn_tot=50,ed=0.2|4,gen_type=WS', -1),
              ], 2500),
            ([('syn:np_tr=20,np_te=50,nn_core=-1,nn_tot=100,ed=5,gen_type=BA', -1),
              ('syn:np_tr=20,np_te=50,nn_core=-1,nn_tot=100,ed=0.08,gen_type=ER', -1),
              ('syn:np_tr=20,np_te=50,nn_core=-1,nn_tot=100,ed=0.2|4,gen_type=WS', -1),
              ], 2500)
        ]
```
